<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robstride_hardware_interface</name>
  <version>0.1.0</version>
  <description>
    ROS 2 package providing a ros2_control hardware interface for RobStride
    CAN actuators (RS00/RS01/RS02/RS03/RS04/RS05/RS06).
  </description>
  <maintainer email="minjokim0703@gmail.com">kmj</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>realtime_tools</depend>
  <depend>robstride_sdk</depend>
  <depend>std_srvs</depend>
  <depend>robstride_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
